"""
Convert natural-language access policies generated by GPT-2 into
Charm-Crypto ABE policy strings.

Example
-------
Input:  "This data can be accessed by users having roles: (Doctor or Researcher)
         and belonging to the Oncology department with clearance level 2."
Output: "(hospitalA.doctor OR hospitalA.researcher) AND hospitalA.oncology
         AND hospitalA.clearance2"
"""
import re


# Roles and departments recognised by the parser
_ROLES = ("doctor", "researcher", "nurse", "admin")
_DEPARTMENTS = ("cardiology", "oncology", "pharmacy", "emergency")


def parse_policy_to_abe_format(policy_text, attributes_prefix):
    """
    Parse *policy_text* and return a Charm-Crypto policy string scoped to
    *attributes_prefix* (e.g. ``"hospitalA"``).

    Returns an empty string if no recognised components are found.
    """
    text = policy_text.lower()

    # Roles → joined with OR
    roles = [f"{attributes_prefix}.{r}" for r in _ROLES if r in text]
    role_expr = ("(" + " OR ".join(roles) + ")") if roles else ""

    # First matching department
    department = next(
        (f"{attributes_prefix}.{d}" for d in _DEPARTMENTS if d in text), None
    )

    # Clearance level (first digit found after "clearance level")
    clearance = None
    m = re.search(r"clearance level (\d+)", text)
    if m:
        clearance = f"{attributes_prefix}.clearance{m.group(1)}"

    components = [c for c in (role_expr, department, clearance) if c]
    return " AND ".join(components)
