import pandas as pd

# Diverse sample rows based on different data types
medical_data = [
    {"MedicalText": "Patient John Doe, 56 years old, diagnosed with hypertension and treated with beta-blockers.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood test result shows elevated cholesterol levels at 240 mg/dL.", "SecurityLabel": "Confidential"},
    {"MedicalText": "MRI of the brain reveals mild signs of atrophy. No acute abnormalities.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient was prescribed 500 mg of amoxicillin for a suspected bacterial infection.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Annual administrative review, insurance data updated, no issues reported.", "SecurityLabel": "Public"},
    {"MedicalText": "Research study participant; data collected on exercise habits, blood pressure readings before and after regimen.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's medical record indicates a history of asthma, treated with inhalers.", "SecurityLabel": "Confidential"},
    {"MedicalText": "CT scan of the chest shows no signs of pneumonia, healthy lung tissue.", "SecurityLabel": "Public"},
    {"MedicalText": "Prescribed a statin to control cholesterol levels following a heart attack in 2018.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Laboratory test shows low iron levels, iron supplements recommended.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient reported minor back pain after lifting heavy weights, no fractures detected on X-ray.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's lab results show glucose level of 145 mg/dL, indicating possible diabetes.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Research indicates a correlation between high-fat diet and increased risk of coronary artery disease.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Administrative staff updated patient contact details and insurance coverage details.", "SecurityLabel": "Public"},
    {"MedicalText": "Chest X-ray shows mild signs of COPD. Follow-up appointment scheduled for further tests.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient underwent colonoscopy; no signs of colorectal cancer, but polyps removed for biopsy.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Medical history: no allergies, no chronic diseases. Regular physical exams show no issues.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient in the oncology department undergoing chemotherapy for lung cancer.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood pressure measured at 145/90, higher than normal range.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Research data indicates a genetic predisposition to breast cancer, patient advised on preventive screening.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient prescribed 10 mg of lorazepam for anxiety. Refill scheduled for next month.", "SecurityLabel": "Confidential"},
    {"MedicalText": "MRI results show clear signs of a herniated disc in the lumbar spine.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's pregnancy test is positive, follow-up ultrasound scheduled for next week.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient administered 5 mg of morphine post-surgery for pain relief.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab results show elevated white blood cell count, indicating possible infection.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's digital health record shows no allergies, medication history includes aspirin.", "SecurityLabel": "Public"},
    {"MedicalText": "CT scan shows evidence of liver cirrhosis. Follow-up required to assess severity.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative data shows the patient has submitted all required forms for insurance verification.", "SecurityLabel": "Public"},
    {"MedicalText": "Research project: study on the impact of sleep deprivation on mental health in adults.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient's primary care physician has been notified of a critical lab result for immediate follow-up.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Cardiac stress test results are normal. No signs of ischemia or arrhythmia.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's BMI is 30, indicating obesity. Recommended dietary changes and exercise regimen.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient was administered a flu vaccine during the last visit. No adverse reactions reported.", "SecurityLabel": "Public"},
    {"MedicalText": "Research found a high prevalence of vitamin D deficiency in the general population, study in progress.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Prescribed a beta-blocker for hypertension, previous medication caused dizziness.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine check-up, patient’s vitals are stable, no underlying health issues detected.", "SecurityLabel": "Public"},
    {"MedicalText": "Lab results indicate low potassium, recommended dietary adjustments and follow-up in 1 week.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Imaging report: X-ray shows signs of early-stage osteoarthritis in the knee joint.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient admitted for observation due to chest pain. ECG results are normal, further monitoring required.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Research on the correlation between smoking and lung cancer rates in different populations.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient prescribed 50 mg of sertraline for anxiety disorder.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Imaging result: MRI shows inflammation in the shoulder joint due to recent injury.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's family history includes type 2 diabetes, hypertension, and heart disease.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Research indicates that regular physical activity reduces the risk of chronic diseases.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient experiencing severe abdominal pain. Initial diagnosis suggests possible appendicitis.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient's name: John Doe, Age: 56, Male, lives in New York.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient has hypertension and a family history of heart disease.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Lab results: Blood pressure is 140/90, cholesterol level is normal.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine checkup: Patient reports no concerns, physically healthy.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient is a 45-year-old female with asthma, allergic to penicillin.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Blood test shows elevated glucose levels indicating potential diabetes.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Prescription for pain relief provided; no further issues noted.", "SecurityLabel": "Public"},
    {"MedicalText": "The patient was referred for cardiac testing due to chest pains.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "The patient is a smoker and has a family history of lung cancer.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "The patient had a minor fall but no fractures were found.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient John Doe, diagnosed with stage 4 lung cancer, undergoing chemotherapy and palliative care.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "MRI report shows a malignant tumor in the left breast, biopsy recommended for further examination.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient experiencing severe chest pain, ECG indicates arrhythmia. Admitted for immediate monitoring.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood test shows elevated liver enzymes, liver biopsy scheduled to assess possible cirrhosis.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "CT scan indicates evidence of brain metastasis from primary lung cancer. Immediate neurology consultation required.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s medical record: history of stroke, currently on anticoagulants and monitoring INR levels.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "CT scan results show signs of early-stage lung cancer in the right lobe. Follow-up imaging in 3 months.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient admitted with symptoms of acute pancreatitis. Lab results confirm diagnosis, treatment initiated.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient undergoing cancer treatment, showing signs of chemotherapy-induced neuropathy, managed with gabapentin.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s medical records indicate recent heart attack, requiring angioplasty and stent placement.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s biopsy results indicate positive for colorectal cancer, requiring surgical intervention.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient in ICU for acute respiratory distress syndrome. Intubation required to manage breathing difficulty.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient prescribed high-dose opioid for cancer pain management. Close monitoring required.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "MRI reveals multiple herniated discs in the lumbar spine, recommended for surgery after physical therapy failure.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Cardiac catheterization shows significant coronary artery blockages, stents inserted to restore blood flow.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient has a known history of multiple miscarriages, undergoing fertility treatments.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with HIV, prescribed antiretroviral therapy. Regular follow-ups scheduled.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient presents with a severe case of sepsis, requiring broad-spectrum antibiotics and vasopressor support.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s genetic test reveals a BRCA1 mutation, indicating a high risk for breast and ovarian cancer.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient under investigation for a suspected rare genetic disorder, whole genome sequencing recommended.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with acute kidney injury, receiving dialysis until renal function improves.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient admitted for post-surgical infection following gallbladder removal, receiving IV antibiotics.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient prescribed immunosuppressive drugs for rheumatoid arthritis, ongoing monitoring of infection risk.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient has a family history of Huntington’s disease, genetic counseling scheduled for risk assessment.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "CT scan indicates mass in the colon, biopsy needed to confirm malignancy.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with severe asthma exacerbation, treated with corticosteroids and bronchodilators.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient presents with sudden vision loss, MRI shows evidence of optic neuritis.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient underwent liver transplant surgery due to end-stage liver failure.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s ECG shows signs of ventricular tachycardia, requiring immediate intervention with cardioversion.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient with end-stage renal disease, dialysis initiated while awaiting kidney transplant.", "SecurityLabel": "Highly Confidential"},
    # Confidential (33 samples)
    {"MedicalText": "Patient’s blood sugar level measured at 180 mg/dL, ongoing management of diabetes with insulin therapy.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Chest X-ray shows early signs of pneumonia, antibiotics prescribed for treatment.", "SecurityLabel": "Confidential"},
    {"MedicalText": "MRI shows mild degenerative changes in the knee joint, physical therapy recommended.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Blood pressure measured at 160/95, patient advised to start antihypertensive medication.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient prescribed atorvastatin for cholesterol management, monitored regularly for side effects.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine physical examination, no signs of any major health concerns. Follow-up in 1 year.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Annual wellness check shows normal vital signs, weight slightly increased. Advised to monitor diet.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Ultrasound shows cyst in the liver, follow-up imaging in 6 months for monitoring.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient reports mild headaches, MRI of the brain normal. Advised to reduce stress levels.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Recent vaccination for influenza given, no adverse reactions observed.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient’s recent blood work indicates low vitamin D levels, prescribed supplements.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine eye examination shows signs of early glaucoma. Follow-up appointment recommended.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient prescribed anti-anxiety medication following recent stressful life events.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine dental check-up shows no cavities, gums healthy.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient reports occasional joint pain, physical therapy recommended for symptom relief.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Blood test results show normal kidney function. No signs of kidney disease.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient’s ECG shows normal sinus rhythm, no arrhythmias detected.", "SecurityLabel": "Confidential"},
    {"MedicalText": "X-ray of the ankle shows no fractures, sprain diagnosed.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine pregnancy test negative. Follow-up appointment scheduled in 2 months.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient’s cholesterol level is at 190 mg/dL, within the normal range.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's immunization records updated, flu vaccine administered for this season.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Physical exam shows mild scoliosis, no immediate treatment required.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with mild asthma, prescribed albuterol inhaler for flare-ups.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient reports fatigue, lab results show slightly low hemoglobin, iron supplements recommended.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Blood pressure consistently above 130/80, patient advised on lifestyle changes and given antihypertensive medication.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Ultrasound of the abdomen shows gallstones, recommended for surgical consultation.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine blood test shows elevated triglyceride levels, lifestyle changes suggested.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient reports mild lower back pain, physical therapy recommended.", "SecurityLabel": "Confidential"},
    # Restricted (33 samples)
    {"MedicalText": "Research study on the effect of sleep deprivation on cognitive function in adults. Preliminary data indicates significant changes.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Study results show a correlation between high-fat diets and cardiovascular disease risk. Further analysis required.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research shows increased risk of cancer among individuals exposed to high levels of radiation. Data under review.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research participant's blood sample analyzed for gene expression. Findings indicate high expression of cancer-related genes.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Study of the genetic predisposition to Alzheimer’s disease in elderly patients. Analysis ongoing.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Medical research study on the effect of new drug on diabetes treatment. Phase II trials complete.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research findings on the impact of air pollution on lung function in children. Data analysis in progress.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Genomic analysis of cancer cell lines. Data suggests new target for treatment under investigation.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research indicates a significant link between obesity and increased risk for diabetes. Further research needed.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Clinical trial data on the effectiveness of a new vaccine for respiratory infections. Final results pending.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Clinical research shows effectiveness of new drug on lowering blood pressure in hypertensive patients.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Genetic testing study on hereditary diseases, identifying new mutation links in certain populations.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Ongoing research into the effects of exercise on mental health outcomes in patients with depression.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Clinical data suggests that a new diet intervention could significantly reduce cholesterol levels.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Cancer study on the effects of immunotherapy in metastatic melanoma patients.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research on the efficacy of a new antidepressant drug. Phase III results showing positive outcomes.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Data collected from participants in a clinical trial for new asthma medication.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Long-term study of the effects of vaping on lung function in adolescents.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Data indicates a strong correlation between smoking and the development of chronic obstructive pulmonary disease (COPD).", "SecurityLabel": "Restricted"},
    {"MedicalText": "Study of the efficacy of cognitive behavioral therapy (CBT) for managing anxiety disorders.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Research on new biomarkers for early detection of Alzheimer's disease.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Clinical trials on the potential of stem cell therapy to treat heart failure.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Data from research on the link between gut microbiota and autoimmune diseases.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Analysis of blood samples from patients with chronic migraines, looking for new treatment pathways.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Phase I trial data shows promising results for new cancer treatment regimen.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Genetic research data on rare neurological disorders, showing patterns of inheritance.", "SecurityLabel": "Restricted"},
    # Public (33 samples)
    {"MedicalText": "General wellness check-up for patient, no significant health concerns reported.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient’s immunization records updated, flu vaccine administered.", "SecurityLabel": "Public"},
    {"MedicalText": "Annual dental check-up, no cavities detected, oral health normal.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient’s height and weight measured, BMI calculated at 24.5, within normal range.", "SecurityLabel": "Public"},
    {"MedicalText": "Routine eye check shows no signs of cataracts or glaucoma. Vision is 20/20.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient reports feeling healthy with no major complaints, follow-up visit in 6 months.", "SecurityLabel": "Public"},
    {"MedicalText": "Routine physical examination reveals a healthy heart rate and normal blood pressure.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient received their flu shot during a routine visit.", "SecurityLabel": "Public"},
    {"MedicalText": "General check-up, no major issues detected during exam.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient reported being in good health, no chronic conditions noted during visit.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient updated personal details in the system, including address and emergency contacts.", "SecurityLabel": "Public"},
    {"MedicalText": "Health screening for cholesterol levels, result indicates normal levels.", "SecurityLabel": "Public"},
    {"MedicalText": "No medical issues identified during annual health check.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient reports no pain, no medication required. Follow-up in 1 year.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient received routine vaccination update, including tetanus and flu shots.", "SecurityLabel": "Public"},
    {"MedicalText": "Medical records show that patient’s blood pressure and cholesterol are normal.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient passed physical fitness test with no issues.", "SecurityLabel": "Public"},
    {"MedicalText": "Routine follow-up appointment, no new health concerns reported.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient received a routine vaccination for pneumonia and hepatitis.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient's vaccination record up to date. Next vaccine due in 6 months.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient’s records show no allergies to medications or food.", "SecurityLabel": "Public"},
    {"MedicalText": "No significant findings from routine examination, patient advised to maintain healthy lifestyle.", "SecurityLabel": "Public"},
    {"MedicalText": "Physical exam reveals normal lung function and clear breath sounds.", "SecurityLabel": "Public"},
    {"MedicalText": "Routine check-up, patient advised to exercise more and maintain a healthy diet.", "SecurityLabel": "Public"},
    {"MedicalText": "Medical records updated after patient’s recent visit to emergency room.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient passed vision test and hearing test with no abnormalities.", "SecurityLabel": "Public"},
    {"MedicalText": "Patient diagnosed with aggressive form of leukemia, undergoing stem cell therapy.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Study results on the effect of diet on blood pressure in hypertensive patients. Data in review.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Routine blood test shows elevated blood glucose, referred for further diabetes testing.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with multi-organ failure following sepsis, undergoing aggressive treatment.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Recent X-ray of the knee shows mild osteoarthritis changes, conservative treatment advised.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Data from clinical trial on the efficacy of a new antidepressant in treating major depression.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient’s cholesterol level is within normal range. No further action required.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient admitted for post-surgical complication following heart valve replacement surgery.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood pressure measured at 135/85, patient advised on reducing sodium intake.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Genetic test results indicate high-risk mutations for breast cancer, preventive mastectomy recommended.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Study on the genetic basis of autoimmune diseases suggests a potential therapeutic target.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient diagnosed with end-stage cirrhosis, awaiting liver transplant. Current MELD score is high.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s immunization record shows all vaccines are up to date.", "SecurityLabel": "Confidential"},
    {"MedicalText": "MRI reveals signs of multiple sclerosis in patient’s brain, prescribed disease-modifying therapy.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient reports occasional back pain, physical therapy suggested for relief.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Data from study on the genetic basis of rare cancers, analysis ongoing.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient undergoing chemotherapy for stage 2 Hodgkin lymphoma, immune function being closely monitored.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "X-ray indicates minor rib fractures, advised to rest and take over-the-counter pain medications.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient’s ECG shows normal rhythm, no abnormalities detected.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient with terminal cancer, palliative care team consulted.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood test shows normal hemoglobin levels. No signs of anemia.", "SecurityLabel": "Confidential"},
    {"MedicalText": "MRI scan shows metastasis of renal cancer to the lungs. Chemotherapy started.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with severe pulmonary fibrosis, oxygen therapy initiated.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Clinical trial results indicate that a new vaccine provides significant protection against influenza strains.", "SecurityLabel": "Restricted"},
    {"MedicalText": "CT scan shows large mass in the chest, suspected lung cancer, further testing required.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Research indicates that Mediterranean diet reduces risk of cardiovascular disease. Data pending.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Routine physical exam shows normal cholesterol levels, follow-up in 6 months.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with rare genetic disorder, genetic counseling ongoing.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Routine pregnancy test negative, follow-up visit scheduled.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Genetic test reveals mutations linked to hereditary neuropathy, treatment options discussed.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "X-ray of the wrist indicates mild sprain, advised to wear a brace for 2 weeks.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with severe scoliosis requiring surgical intervention, pre-op imaging performed.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient reports persistent cough, chest X-ray indicates mild pneumonia.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with chronic kidney disease, awaiting dialysis for advanced treatment.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Blood sugar levels under control with current insulin regimen, follow-up appointment next month.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Clinical data on the effects of new medication on reducing Alzheimer’s disease progression.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient's biopsy results indicate presence of malignant melanoma, surgical excision planned.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient presents with signs of severe allergic reaction, epinephrine administered.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Study on the correlation between environmental factors and respiratory health in urban populations.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient diagnosed with severe anemia, receiving iron transfusions.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Routine dental check-up indicates no issues, follow-up visit in 6 months.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with acute myocardial infarction, undergoing angioplasty.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with rare genetic disorder, genetic counseling ongoing.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient undergoing post-operative monitoring following major abdominal surgery.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Data from a clinical trial on the impact of a new heart disease medication showing moderate success.", "SecurityLabel": "Restricted"},
    {"MedicalText": "MRI scan shows large mass in the brain, surgery scheduled for tumor removal.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient undergoing stem cell therapy for autoimmune disorder, closely monitored for side effects.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Routine screening for colorectal cancer showed normal results, follow-up in 5 years.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient admitted with high fever, suspected infection, blood cultures ordered.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient’s weight is stable, with healthy BMI. No intervention needed at this time.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Routine check-up shows normal lung function, no issues detected.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Blood test shows normal liver function, no signs of disease.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient’s family history includes hereditary colon cancer, patient to undergo genetic testing.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient reports no recent medical issues, advised to continue regular exercise and balanced diet.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Clinical study on the impact of exercise on cholesterol levels in elderly individuals.", "SecurityLabel": "Restricted"},
    {"MedicalText": "X-ray indicates signs of osteoporosis in the lumbar spine, physical therapy recommended.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient receiving a regular flu vaccine as part of routine annual health care.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Post-surgery complications including infection, patient on broad-spectrum antibiotics.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Routine check-up shows no significant issues. Follow-up scheduled in one year.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Study on the genetic markers of Alzheimer’s disease shows promising leads for early diagnosis.", "SecurityLabel": "Restricted"},
    {"MedicalText": "Patient diagnosed with early-stage diabetes, lifestyle interventions advised.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient diagnosed with stage 3 non-Hodgkin lymphoma, treatment plan in progress.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Physical exam shows healthy reflexes, normal heart rate, and blood pressure.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient receiving regular dialysis for end-stage renal failure.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with seasonal allergies, prescribed antihistamines.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's family history includes hereditary colon cancer, patient to undergo genetic testing.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Patient diagnosed with early-stage rheumatoid arthritis, physical therapy and medication advised.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: John Doe, Age: 45, Gender: Male, Date of Birth: 1979-08-14, Insurance: ABC Health, Policy Number: 123456", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing entry for patient's chemotherapy treatment on 2024-03-15, Procedure Code: 12345, Total Cost: $5000", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's prescription for Metformin 500mg, 1 tablet daily for type 2 diabetes, prescribed on 2024-01-10.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: John Smith, Patient ID: 124578, Appointment Date: 2024-03-01, Doctor: Dr. Jane Brown, Department: Cardiology.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing entry for outpatient clinic visit, Doctor: Dr. Samuel Lee, Date of Visit: 2024-02-05, Procedure Code: 6789, Amount: $200.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Mary Johnson, Age: 60, Gender: Female, Address: 456 Oak St, Springfield, Insurance: XYZ Health, Policy No: 789101", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription for Lisinopril 10mg daily for hypertension, prescribed on 2024-03-12, refill allowed for 1 month.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient admission: Jane Smith, Age: 50, Admission Date: 2024-02-25, Admission Reason: Heart Failure, Attending Doctor: Dr. Emily White.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing for a lab test on 2024-02-21, Total Cost: $150, Lab Procedure Code: 25478, Test: Lipid Profile.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription for Warfarin 5mg, 1 tablet daily, for prevention of stroke due to atrial fibrillation, written on 2024-01-29.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Alex Brown, Age: 40, Gender: Male, Insurance Provider: United Health, Policy Number: 112233", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative note: Patient Alex Brown rescheduled appointment from 2024-04-01 to 2024-04-10, with Dr. Steven Green.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Patient care services for flu treatment on 2024-02-20, Doctor: Dr. George Miller, Total: $120.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Susan Lee, Age: 70, Gender: Female, Address: 123 Elm St, Insurance: ABC Health, Policy No: 345678", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Statin (Simvastatin 20mg), one tablet at night for hyperlipidemia, written by Dr. Sarah Anderson on 2024-02-15.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: James White, Age: 55, Appointment scheduled with Dr. Patricia Clark, Neurology, on 2024-03-10.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Procedure code 10010, physical therapy for back pain on 2024-03-11, Amount: $75", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Jessica Garcia, Age: 35, Gender: Female, Insured by: XYZ Health, Policy No: 445566", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Albuterol inhaler 90mcg, 2 puffs as needed for asthma, prescribed by Dr. William King on 2024-03-02.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative: Patient William Scott, Age: 42, Scheduled for MRI on 2024-03-20, Physician: Dr. Elizabeth Moore.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing entry: Emergency Room visit on 2024-03-04, Procedure Code: 5489, Total: $800", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Robert Martinez, Age: 29, Gender: Male, Insured by: HealthPlus, Policy ID: 234567", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient's prescription for Amitriptyline 25mg at bedtime for chronic pain, prescribed on 2024-03-14.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: Sarah Carter, Age: 48, Scheduled for follow-up on 2024-03-19, Doctor: Dr. Arthur Powell.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Blood test for CBC, total: $95, Date: 2024-02-17, Lab Procedure Code: 15932.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Olivia Thompson, Age: 60, Gender: Female, Address: 789 Birch Ave, Policy Number: 345123, Insurance Provider: HealthFirst", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Furosemide 40mg for edema, prescribed on 2024-02-28.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Thomas Lewis, Age: 75, Male, Hospital Admission Reason: Acute Stroke, Admission Date: 2024-02-26.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Billing: Patient's physiotherapy for stroke recovery, Total: $220, Date: 2024-02-22.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Prescription: Insulin 10 units for type 1 diabetes management, prescribed on 2024-03-11.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Administrative record: Patient's discharge summary from the hospital on 2024-03-05, Discharge Diagnosis: Stroke.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Name: George Hill, Age: 65, Insured by: BlueCross, Policy Number: 567890, Address: 1000 Pine St.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Emergency services for heart attack diagnosis on 2024-03-13, Amount: $1200, Procedure Code: 65432.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Prescription: Diazepam 10mg for anxiety, written by Dr. Rachel Fox on 2024-03-02.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: Patient appointment scheduled with Dr. Helen Moore for CT scan on 2024-03-08.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Lab tests for kidney function, Total: $320, Test: Creatinine, Date: 2024-02-19.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Jack Thompson, Age: 50, Gender: Male, Policy No: 122334, Insurance: United Healthcare", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Pantoprazole 40mg for GERD, prescribed on 2024-03-06.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: Anna Brown, Age: 38, Scheduled for colonoscopy on 2024-03-15, Doctor: Dr. Adam White.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Procedure for MRI on 2024-02-25, Amount: $450, Procedure Code: 3221", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Emma Evans, Age: 32, Gender: Female, Address: 333 Maple St, Insured by: MedCare, Policy Number: 678901", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Oxycodone 10mg for post-surgery pain management, prescribed on 2024-02-19.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Administrative: Mark Peterson, Age: 60, Appointments rescheduled for 2024-03-18, Reason: Severe Headache.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: Outpatient procedure for knee arthroscopy, Date: 2024-02-23, Total: $350", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Laura Kim, Age: 26, Gender: Female, Insurance Provider: CarePlan, Policy Number: 981234", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Atorvastatin 20mg for cholesterol control, prescribed on 2024-03-17.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative: Patient’s appointment canceled due to personal reasons, new appointment on 2024-04-02.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing: CT scan for abdominal pain on 2024-02-28, Amount: $600, Procedure Code: 56123", "SecurityLabel": "Confidential"},
    {"MedicalText": "Name: Kevin Scott, Age: 39, Gender: Male, Address: 888 Birch St, Policy No: 123789, Insurance Provider: HealthyCare", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Clonazepam 0.5mg for panic disorder, prescribed on 2024-03-09.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: Patient admitted to ICU for complications, Dr. Linda Jones assigned as attending physician.", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Billing: Outpatient visit for follow-up, Doctor: Dr. Joseph Black, Date: 2024-03-03, Total: $150.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Patient: Jessica White, Age: 50, Gender: Female, Insured by: Global Health, Policy No: 567890", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription: Propranolol 20mg for hypertension, prescribed on 2024-02-25.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative note: Patient: Claire Harris, Age: 40, Follow-up appointment with Dr. John Lewis scheduled for 2024-03-05.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Billing entry for vaccination (flu shot) on 2024-02-28, Total Cost: $30.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Name: Nina Moore, Age: 65, Gender: Female, Policy No: 654321, Insurance: MedCarePlus", "SecurityLabel": "Confidential"},
    {"MedicalText": "Prescription for Ranitidine 150mg, 1 tablet daily for heartburn, written by Dr. Jenny Green on 2024-02-22.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Administrative record: Patient’s emergency contact updated on 2024-03-01, Contact Name: David Moore.", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: CBC, Hemoglobin: 14.5 g/dL, WBC: 6,500/µL, Platelets: 220,000/µL, Date: 2024-03-01", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Lipid Profile, Total Cholesterol: 210 mg/dL, LDL: 120 mg/dL, HDL: 50 mg/dL, Triglycerides: 150 mg/dL, Date: 2024-03-03", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Thyroid Function, TSH: 3.5 µIU/mL, Free T4: 1.2 ng/dL, Date: 2024-03-02", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Basic Metabolic Panel, Sodium: 140 mmol/L, Potassium: 4.0 mmol/L, Glucose: 98 mg/dL, Date: 2024-02-28", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Liver Function, AST: 25 IU/L, ALT: 30 IU/L, Bilirubin: 0.8 mg/dL, Date: 2024-02-26", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Blood Glucose, Fasting: 105 mg/dL, 2-hour Postprandial: 140 mg/dL, Date: 2024-03-05", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Hemoglobin A1c, Result: 6.8%, Date: 2024-02-27", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Urinalysis, Protein: Negative, Glucose: Negative, Specific Gravity: 1.010, Date: 2024-03-01", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Complete Metabolic Panel, Calcium: 9.2 mg/dL, Creatinine: 0.8 mg/dL, BUN: 14 mg/dL, Date: 2024-02-25", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Vitamin D Levels, 25-OH Vitamin D: 35 ng/mL, Date: 2024-02-24", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: B-type Natriuretic Peptide (BNP), Result: 180 pg/mL, Date: 2024-03-02", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Lab Test: Hemoglobin A1c, Result: 7.2%, Date: 2024-03-05", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Prostate Specific Antigen (PSA), Result: 2.5 ng/mL, Date: 2024-03-04", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Coagulation Profile, INR: 1.1, PT: 12.0 sec, aPTT: 32 sec, Date: 2024-02-20", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: D-dimer, Result: 400 ng/mL, Date: 2024-02-22", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: C-Reactive Protein (CRP), Result: 2.5 mg/L, Date: 2024-02-18", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Blood Culture, Result: Negative, Date: 2024-03-03", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Blood Urea Nitrogen (BUN), Result: 12 mg/dL, Date: 2024-03-06", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Urine Culture, Result: No Growth, Date: 2024-02-23", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Creatinine, Result: 1.0 mg/dL, Date: 2024-03-02", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Folic Acid, Result: 7.5 ng/mL, Date: 2024-02-27", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Comprehensive Metabolic Panel, Sodium: 138 mmol/L, Potassium: 3.5 mmol/L, Glucose: 95 mg/dL, Date: 2024-02-24", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Complete Blood Count, Hemoglobin: 13.2 g/dL, WBC: 5,200/µL, Platelets: 250,000/µL, Date: 2024-03-07", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Vitamin B12, Result: 400 pg/mL, Date: 2024-03-01", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: HLA-B27, Result: Positive, Date: 2024-02-20", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Anti-CCP, Result: Negative, Date: 2024-03-04", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: HIV-1/2 Antibody, Result: Negative, Date: 2024-03-02", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Lab Test: Hepatitis C Antibody, Result: Positive, Date: 2024-03-06", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Lab Test: Hepatitis B Surface Antigen, Result: Negative, Date: 2024-03-08", "SecurityLabel": "Highly Confidential"},
    {"MedicalText": "Lab Test: Testosterone, Result: 400 ng/dL, Date: 2024-02-22", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Estrogen, Result: 250 pg/mL, Date: 2024-02-18", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Glucose, Result: 98 mg/dL, Date: 2024-03-03", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: CBC, Hemoglobin: 15.2 g/dL, WBC: 7,000/µL, Platelets: 230,000/µL, Date: 2024-02-25", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Free T3, Result: 2.5 ng/dL, Date: 2024-02-26", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Free T4, Result: 1.5 ng/dL, Date: 2024-02-21", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Albumin, Result: 4.5 g/dL, Date: 2024-03-05", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Total Protein, Result: 6.8 g/dL, Date: 2024-03-04", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Magnesium, Result: 2.1 mg/dL, Date: 2024-02-28", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Lactic Acid, Result: 2.2 mmol/L, Date: 2024-02-27", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: DHEA, Result: 140 µg/dL, Date: 2024-03-02", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Calcium, Result: 9.0 mg/dL, Date: 2024-03-07", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Potassium, Result: 3.8 mmol/L, Date: 2024-02-25", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: ALP, Result: 75 IU/L, Date: 2024-03-06", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Bilirubin, Result: 0.9 mg/dL, Date: 2024-02-28", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Total Cholesterol, Result: 190 mg/dL, Date: 2024-02-20", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Triglycerides, Result: 150 mg/dL, Date: 2024-02-21", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: HCG, Result: Negative, Date: 2024-03-05", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: Ferritin, Result: 150 ng/mL, Date: 2024-03-03", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: CRP, Result: 1.0 mg/L, Date: 2024-02-24", "SecurityLabel": "Confidential"},
    {"MedicalText": "Lab Test: BUN, Result: 16 mg/dL, Date: 2024-03-01", "SecurityLabel": "Confidential"}

]

# Creating the DataFrame
df = pd.DataFrame(medical_data)

# Saving to a CSV
df.to_csv('medical_data.csv', index=False)

print("CSV with medical data has been generated successfully!")

